### ISSUE TITLE
Implement deleting repeated words

### ISSUE THREAD

**Issue by MichalDolata** [MichalDolata/text-transformer#12]
Jako   użytkownik mogę eliminować powtarzające się wyrazy w bezpośrednim sąsiedztwie   (Wyślij do do mnie wiadomość -> Wyślij do mnie wiadomość)

•  Zamiana dwóch powtarzających się wyrazów na jeden: do do -> do    
• Zamiana dowolnej liczby powtarzających się wyrazów: do do do ->   do     
• Zamiana wszystkich powtórzeń w ramach tekstu: do do po po -> do   po    
• Działa prawidłowo dla wszystkich znaków UTF-8

**Comment by mdziardziel** [comment]
Bierzemy pod uwagę wielkość lite oraz znaki interpunkcyjne? Według mnie specyfikacja wskazuje na branie obu pod uwagę, chociaż nie jest do końca jasna.

PRZYKŁADY
Wrażliwość na wielkość liter:
Do do po Po -> Do do po Po
Brak wrażliwości (przy okazji priorytet dla wielkich liter):
Do do po po -> Do Po
Wrażliwość na znaki interpunkcyjne:
do do, po po. -> do do, po po.
Brak wrażliwości na znaki interpunkcyjne (oraz priorytet dla wyrazów ze znakami):
do do, po po. -> do, po.

@MichalDolata wybieramy któryś wariant czy dopytujemy się klienta jak ma być?

**Comment by MichalDolata** [comment]
@mdziardziel 
Jak dla mnie lepsza jest wersja z brakiem wrażliwości zarówno na wielkość liter oraz znaki interpunkcyjne. Przypomnij mi jutro przed zajęciami to zapytam jeszcze klienta co o tym sądzi
